# Generated by Django 4.2.5 on 2023-11-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='points',
            options={'verbose_name': 'Point'},
        ),
        migrations.RenameField(
            model_name='points',
            old_name='additions',
            new_name='score1',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='complementaires',
            new_name='score2',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='divisions',
            new_name='score3',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='multiplications',
            new_name='score4',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='soustractions',
            new_name='score5',
        ),
    ]
