# Generated by Django 4.2.5 on 2023-11-29 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_points_options_rename_additions_points_score1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanger',
            name='resultat',
            field=models.IntegerField(default=0),
        ),
    ]
