# Generated by Django 4.2.5 on 2023-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_exchanger_resultat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchanger',
            old_name='resultat',
            new_name='score_addition',
        ),
        migrations.AddField(
            model_name='exchanger',
            name='score_division',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='score_multiplication',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='score_soustraction',
            field=models.IntegerField(default=0),
        ),
    ]
