# Generated by Django 4.2.5 on 2024-02-14 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_resultat_exchanger_score_addition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='REPONSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='points',
            options={},
        ),
        migrations.AddField(
            model_name='exchanger',
            name='Duree',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='duree_connexion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='horaire1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='nombreQuestions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='reponsesFausses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='reponsesFaussesPourcentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='reponsesJustes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='reponsesJustesPourcentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='tempsMoyenCentieme',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplication', models.IntegerField(default=0)),
                ('multiplicationNiveau', models.IntegerField(default=0)),
                ('multiplicationALaSuite', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
