# Generated by Django 4.2.5 on 2024-02-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_reponse_alter_points_options_exchanger_duree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanger',
            name='reponseEleve',
            field=models.FloatField(default=0),
        ),
    ]
