# Generated by Django 4.2.5 on 2024-03-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_exchanger_reponseeleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanger',
            name='a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exchanger',
            name='b',
            field=models.IntegerField(default=0),
        ),
    ]
