# Generated by Django 4.2.5 on 2024-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_exchanger_a_exchanger_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='multiplicationsFaussesALaSuite',
            field=models.IntegerField(default=0),
        ),
    ]
