# Generated by Django 4.2.5 on 2024-03-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_score_multiplicationsfaussesalasuite'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchanger',
            name='url',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
